const { box } = require("./functions.js")

// Generated by Qodo Gen

describe('box', () => {

    // The function returns a valid SVG rect element
    it('should return a valid SVG rect element when called', () => {
      const rect = box();
      expect(rect).toBeInstanceOf(SVGRectElement);
      expect(rect.namespaceURI).toBe("http://www.w3.org/2000/svg");
    });
});
